Volunteer metrics defination
DevDataPlatform/dbt_sneha pull request #20
Opened 2023-08-07 11:48 UTC by abikarmakar

volunteer_open_count, female_volunteer_count, male_volunteer_count as per date.

2023-08-07 15:05 UTC, vinod-rajasekaran requested changes

2023-08-07 15:05 UTC, vinod-rajasekaran commented on models/production/volunteer/raw/volunteer_training.sql
can we cast these earlier - best practice is to do this earlier in intermediate schema itself

2023-08-07 15:05 UTC, vinod-rajasekaran commented on models/production/volunteer/raw/volunteer_metrics_definition.sql
Please create a new aggregated folder and push this to there

2023-08-08 06:32 UTC, abikarmakar commented on models/production/volunteer/raw/volunteer_training.sql
Done.

2023-08-08 06:59 UTC, vinod-rajasekaran approved these changes

2023-08-08 07:04 UTC, merged