fix/mwra metrics and restructure mwra lineage
DevDataPlatform/dbt_sneha pull request #21
Opened 2023-08-09 09:57 UTC by swapneelrane

@siddhant3030 , @vinod-rajasekaran  ... sorry this PR has so many commits, but most of them are new code is to either update the mwra metrics definitions or to restructure the lineage so that metrics for Program, CO, M&E-Metrics, and Distribution dashboards are pre-calculated

2023-08-14 04:09 UTC, vinod-rajasekaran requested changes

2023-08-14 04:09 UTC, vinod-rajasekaran commented on dbt_project.yml
can we leave out the changes on this file ? we have modified the generate_schema macro to adapt to multiple people working and it should automatically do this. For any development scenario, all you have to do is create a target say Swapneel and push schema to Swapneel also. This will then create two schemas which ft with staging:

Swapneel_intermediate (similar to intermediate)
Swapneel (similar to prod)

2023-08-14 04:09 UTC, vinod-rajasekaran commented on models/production/mwra/aggregated/mwra_metrics_normalized.sql
Can we make lines 12-24 be not database case but free text i.e. 1. Open Cases instead of 1. open_cases ? etc..
-

2023-08-14 05:27 UTC, swapneelrane commented on models/production/mwra/aggregated/mwra_metrics_normalized.sql
Done.

2023-08-14 05:30 UTC, swapneelrane commented on dbt_project.yml
Done.

2023-08-16 05:20 UTC, siddhant3030 approved these changes

2023-08-16 05:21 UTC, merged